title: Tinkr.de
baseurl: ""
url: "https://tinkr.de"
copyright: Sebastian Schuster

remote_theme: shostakovich/zaunkoenig
plugins:
  - jekyll-feed

sass:
  style:            :compressed

theme: jekyll-theme-cayman